### ISSUE TITLE
Error on Turkey Lurkey

### ISSUE THREAD

**Issue by colah-blackhand** [Beast-Masters-addons/FistfulOfTurkeyLurkey#1]
I am getting these two errors when mousing over a Rogue:

Message: Interface/AddOns/FistfulOfTurkey/addon/tracker.lua:77: attempt to call upvalue 'UnitBuff' (a nil value)
Time: Sun Nov 24 21:05:01 2024
Count: 6
Stack: Interface/AddOns/FistfulOfTurkey/addon/tracker.lua:77: attempt to call upvalue 'UnitBuff' (a nil value)
[string "@Interface/AddOns/FistfulOfTurkey/addon/tracker.lua"]:77: in function `getBuff'
[string "@Interface/AddOns/FistfulOfTurkey/addon/tracker.lua"]:204: in function `need'
[string "@Interface/AddOns/FistfulOfTurkey/addon/tracker.lua"]:231: in function `?'
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BetterBags/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BetterBags/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 achievement_name = "Turkey Lurkey"
 name = "FistfulOfLove"
 orderedModules = <table> {
 }
 missingCombo = <table> {
 }
 missing = <table> {
 }
 achievement = "[Turkey Lurkey]"
 data = <table> {
 }
 baseName = "FistfulOfTurkey"
 enabledState = true
 defaultModuleState = true
}
unit = "mouseover"
find_spellId = 61781
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "mouseover"
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'UnitBuff' (a nil value)"
UnitBuff = nil

=================================================================

Message: Interface/AddOns/FistfulOfTurkey/addon/tracker.lua:77: attempt to call upvalue 'UnitBuff' (a nil value)
Time: Sun Nov 24 21:03:44 2024
Count: 1
Stack: Interface/AddOns/FistfulOfTurkey/addon/tracker.lua:77: attempt to call upvalue 'UnitBuff' (a nil value)
[string "@Interface/AddOns/FistfulOfTurkey/addon/tracker.lua"]:77: in function `getBuff'
[string "@Interface/AddOns/FistfulOfTurkey/addon/tracker.lua"]:204: in function `need'
[string "@Interface/AddOns/FistfulOfTurkey/addon/tracker.lua"]:227: in function `?'
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BetterBags/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BetterBags/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 achievement_name = "Turkey Lurkey"
 name = "FistfulOfLove"
 orderedModules = <table> {
 }
 missingCombo = <table> {
 }
 missing = <table> {
 }
 achievement = "[Turkey Lurkey]"
 data = <table> {
 }
 baseName = "FistfulOfTurkey"
 enabledState = true
 defaultModuleState = true
}
unit = "target"
find_spellId = 61781
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "target"
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'UnitBuff' (a nil value)"
UnitBuff = nil

**Comment by datagutten** [comment]
This should be fixed in 2bd57ca7badf764dd1f3f960e76382f6a1b2e5d3 released as v1.4.2
